# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.srcs/sources_1/ip/basex_pcs_pma_1/basex_pcs_pma_1.xci
# IP: The module: 'basex_pcs_pma_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/ip_0/basex_pcs_pma_1_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basex_pcs_pma_1_gt || ORIG_REF_NAME==basex_pcs_pma_1_gt} -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/ip_0/synth/basex_pcs_pma_1_gt_ooc.xdc

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/ip_0/synth/basex_pcs_pma_1_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==basex_pcs_pma_1_gt || ORIG_REF_NAME==basex_pcs_pma_1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/basex_pcs_pma_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'basex_pcs_pma_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/synth/basex_pcs_pma_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'basex_pcs_pma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/synth/basex_pcs_pma_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'basex_pcs_pma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/synth/basex_pcs_pma_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'basex_pcs_pma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.srcs/sources_1/ip/basex_pcs_pma_1/basex_pcs_pma_1.xci
# IP: The module: 'basex_pcs_pma_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/ip_0/basex_pcs_pma_1_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basex_pcs_pma_1_gt || ORIG_REF_NAME==basex_pcs_pma_1_gt} -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/ip_0/synth/basex_pcs_pma_1_gt_ooc.xdc

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/ip_0/synth/basex_pcs_pma_1_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==basex_pcs_pma_1_gt || ORIG_REF_NAME==basex_pcs_pma_1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/basex_pcs_pma_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'basex_pcs_pma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/synth/basex_pcs_pma_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'basex_pcs_pma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/synth/basex_pcs_pma_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'basex_pcs_pma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/leezz/OneDrive/taxi/example/ZCU106/fpga/fpga_1g/fpga.gen/sources_1/ip/basex_pcs_pma_1/synth/basex_pcs_pma_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'basex_pcs_pma_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
